#!/bin/bash

# pipe separated list of synology users to exclude
SKIP_USERS="admin"


Reference
https://wiki2.dovecot.org/Migration

# todo
# install pub key on mac server
# install gargs
# test master auth for every user, report back issues

# prepare synology
# install nano/pico
curl http://screenshare.tech/synology/dsm6.2_nano.tgz -o nano.tgz
tar xzf nano.tgz && mv nano pico /usr/local/bin/

### setup master authentication




check_users() {
  ls /var/services/homes/ | grep -viE "^${SKIP_USERS}|@eaDir$"
