#!/bin/bash

# Should be run as root from Synology Task Manager on reboot
# 

# output stderr to stdout
exec 2>&1

FILE=/var/tmp/nginx/smb.netbios.aliases.conf

# if run non-interactive, sleep for 120 seconds
#[ -z "$PS1" ] && sleep 30

#echo first
#cat "$FILE"

if [ -f "$FILE" ] ; then
  echo "VFS_FRUIT script could not run because $FILE already exists"
  cat "$FILE"
  exit 1
fi

#echo before
#cat "$FILE"

# Stop Samba
/usr/syno/sbin/synoservicecfg --stop samba

#echo after stop
#cat "$FILE"


sleep 10

# Create the new conf file if it doesn't exist
echo "vfs objects = fruit
fruit:aapl = yes
fruit:encoding = native
fruit:locking = none
fruit:metadata = stream
fruit:resource = file" >> "$FILE"

# Start Samba
/usr/syno/sbin/synoservicecfg --start samba

#echo after start
#cat "$FILE"

exit

echo
echo
echo --------------------------------------
echo
echo "kstreet.npc.org was rebooted and the Samba script was run."
echo
echo "cat $FILE"
echo ----
cat "$FILE"

exit 0
